stages:
  - test
  - build

tests:
  image: python:3.9-slim-buster
  stage: test
  before_script:
    - apt-get update && apt-get install make gcc -y
  script:
    - make test

build_image:
  stage: build
  variables:
    IMAGE_NAME: justivo/demo-app
    IMAGE_TAG: ci-cd-app-1.0
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .