tests:
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make gcc -y
  script:
    - make test

  build:
    script:
      - docker build -t justivo/demo-app:ci-cd-app-1.0 .